---
- name: Install dotnet core SDK
  hosts: all
  become: yes

  tasks:
    - name: Install packages-microsoft-prod.deb 
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb 

    - name: Update repositories cache and install apt-transport-https
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes

    - name: Install dotnet-sdk-3.1
      apt:
        name: dotnet-sdk-3.1
        state: present



