- name: Add .ssh key
  hosts: "*"
  tasks:
    - name: Ensure .ssh directory exists.
      ansible.builtin.file:
        dest: "{{ lookup('env', 'HOME') }}/.ssh"
        mode: '0700'
        state: directory

    - name: Install ssh key
      ansible.builtin.copy:
        src: "{{ (playbook_dir + '/../files/ssh/id_rsa') | realpath }}"
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
        mode: '0600'

    - name: Install ssh public key
      ansible.builtin.copy:
        src: "{{ (playbook_dir + '/../files/ssh/id_rsa.pub') | realpath }}"
        dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
        mode: '0600'
