- name: install latest qemu-guest-agent
  hosts: "*"
  tasks:
    - name: install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: latest
        update_cache: true
      become: true
