- name: Install zsh and dotfiles
  hosts: "*"
  tasks:
    - name: clone dotfiles
      ansible.builtin.git:
        repo: 'https://github.com/jawee/.dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/.dotfiles"

    - name: install stow, zsh, fzf
      ansible.builtin.apt:
        pkg:
          - stow
          - zsh
          - fzf
      become: true

    - name: Change shell
      user:
        name: figge
        shell: /bin/zsh
      become: true

    - name: Oh-My-Zsh
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
      become_user: figge

    - name: Install zsh-autosuggestions
      ansible.builtin.git:
        repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
        dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"

    - name: Checking if .zshrc already exists
      stat:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
      register: file_data

    - name: Remove .zshrc if it exists and is not a stowed file
      file:
        path: "{{ lookup('env', 'HOME') }}/.zshrc"
        state: absent
      when: file_data.stat.islnk is defined and file_data.stat.islnk == False

    - name: Stow dotfiles
      shell: cd $HOME/.dotfiles/wsl-ubuntu && ./install
