---
- name: Install dotnet core SDK
  hosts: all
  become: true

  tasks:
    - name: Install dotnet6
      ansible.builtin.apt:
        name: dotnet6
        state: present
        update_cache: true

    - name: Install dotnet7
      ansible.builtin.apt:
        name: dotnet7
        state: present

    - name: Install dotnet8
      ansible.builtin.apt:
        name: dotnet8
        state: present
