---
- name: Install golang
  hosts: all
  become: yes

  tasks:
    - name: Get file
      command: curl -OL https://go.dev/dl/go1.20.1.linux-amd64.tar.gz

    - name: Remove old install if exists
      file:
        state: absent
        path: /usr/local/go

    - name: Install
      command: tar -C /usr/local -xzf go1.20.1.linux-amd64.tar.gz

    - name: Remove archive
      command: rm go1.20.1.linux-amd64.tar.gz

    - name: Install gopls
      command: go install golang.org/x/tools/gopls@latest
