---
- name: Install Plex and HDR packages.
  hosts: all
  become: yes

  tasks:
    - name: Update repositories cache and install additional packages
      apt:
        pkg:
          - ocl-icd-libopencl1
          - beignet-opencl-icd
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Plex.
      apt:
        deb: https://downloads.plex.tv/plex-media-server-new/1.22.0.4163-d8c4875dd/debian/plexmediaserver_1.22.0.4163-d8c4875dd_amd64.deb
