- name: Install neovim
  hosts: "*"
  gather_facts: true
  tasks:
    - name: Install build dependencies (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.apt:
        pkg:
          - ninja-build
      become: true

    - name: Install lua-language-server (MacOS)
      when: ansible_distribution == 'MacOSX'
      homebrew:
        name: lua-language-server
        state: present
        update_homebrew: true

    - name: Clone repo (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.git:
        repo: 'https://github.com/LuaLS/lua-language-server'
        dest: "{{ lookup('env', 'HOME') }}/lua-language-server"
        update: yes
        force: yes
        version: master

    - name: Ensure make.sh is executable (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/lua-language-server/make.sh"
        mode: '0755'

    - name: Build and install (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      shell: "cd {{ lookup('env', 'HOME') }}/lua-language-server && ./make.sh"
      become: true

    - name: Make lua-language-server usable by all users (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/lua-language-server/bin/lua-language-server"
        mode: '0755'

    - name: Make log directory world-writable (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/lua-language-server/log"
        mode: '0777'
        state: directory
        recurse: true
      become: true

    - name: Symlink lua-language-server to /usr/local/bin (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.file:
        src: "{{ lookup('env', 'HOME') }}/lua-language-server/bin/lua-language-server"
        dest: /usr/local/bin/lua-language-server
        state: link
      become: true

