- name: Install neovim
  hosts: "*"
  tasks:
    - name: clone neovim
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ lookup('env', 'HOME') }}/neovim"

    - name: install build dependencies
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen
      become: true

    - name: install plug
      ansible.builtin.shell: |
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

    - name: build neovim
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"

    - name: install neovim
      become: true
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
