- name: Install nodejs
  hosts: all

  tasks:
    - name: nodesource script
      shell: curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
      become: true

    - name: install node
      apt:
        name: nodejs
        state: latest
        update_cache: true
      become: true
