---
- name: Install golang
  hosts: all
  become: yes

  tasks:
    - name: Remove old install if exists
      file:
        state: absent
        path: /usr/local/go

    - name: Download and install
      unarchive:
        src: https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
        dest: /usr/local
        remote_src: yes 

    - name: Install gopls
      command: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest
