- name: Install nodejs
  hosts: all

  tasks:
    - name: Nodesource 24.x download
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_24.x
        dest: /tmp/
        mode: '0755'
      become: true

    - name: Execute setup 24.x script.
      ansible.builtin.command: /tmp/setup_24.x
      become: true
      # noqa no-changed-when

    - name: Remove setup 24.x script
      ansible.builtin.file:
        path: /tmp/setup_24.x
        state: absent
      become: true

    - name: Install node
      ansible.builtin.apt:
        name: nodejs
        state: latest
        update_cache: true
      become: true
      # noqa package-latest
