---
- name: Install newer version of VIM
  hosts: all
  become: yes

  tasks:
    - name: Add jonathonf/vim repository 
      apt_repository:
        repo: ppa:jonathonf/vim

    - name: install vim 
      apt:
        update_cache: yes
        name: vim
        state: latest
    
    - name: Copy over .vimrc
      template: 
        src: "../files/.vimrc" 
        dest: "/home/figge/.vimrc"

    - name: Set permissions on .vimrc
      file:
        path: /home/figge/.vimrc
        owner: figge
        group: figge
