- name: Install neovim
  hosts: "*"
  gather_facts: true
  tasks:

    - name: Clone neovim master
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ lookup('env', 'HOME') }}/neovim"
        update: true
        force: true
        version: master

    - name: Checkout neovim stable
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ lookup('env', 'HOME') }}/neovim"
        update: true
        force: true
        version: stable

    - name: Install build dependencies (Ubuntu)
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen
      become: true
      when: ansible_distribution == 'Ubuntu'

    - name: Install build dependencies (MacOS)
      community.general.homebrew:
        name:
          - ninja
          # - cmake  #disabled, fails when ran
          - gettext
          - curl
        state: present
        update_homebrew: true
      when: ansible_distribution == 'MacOSX'

    # - name: Clean neovim build
    #   ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/neovim && make clean && make distclean"
    #   become: true
    #   # noqa no-changed-when

    - name: Build neovim
      ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo -j 20"
      become: true
      # noqa no-changed-when

    - name: Install neovim
      become: true
      ansible.builtin.shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install CMAKE_BUILD_TYPE=RelWithDebInfo"
      # noqa no-changed-when
