- name: Install latest qemu-guest-agent
  hosts: "*"
  tasks:
    - name: Install qemu-guest-agent
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: latest
        update_cache: true
      become: true
      # noqa package-latest
