- name: Install neovim
  hosts: "*"
  gather_facts: true
  tasks:

    - name: Clone neovim
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ lookup('env', 'HOME') }}/neovim"
        update: yes
        force: yes

    - name: Install build dependencies (Ubuntu)
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen
      become: true
      when: ansible_distribution == 'Ubuntu'

    - name: Install build dependencies (MacOS)
      homebrew:
        name: 
          - ninja
          # - cmake  #disabled, fails when ran
          - gettext 
          - curl
        state: present
        update_homebrew: true
      when: ansible_distribution == 'MacOSX'

    - name: Clean neovim build
      shell: "cd {{ lookup('env', 'HOME')}}/neovim && make clean && make distclean"
      become: true

    - name: Build neovim
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
      become: true

    - name: Install neovim
      become: true
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
