---
- name: Install Plex and HDR packages.
  hosts: proxmox-plex
  become: yes

  tasks:
    - name: Update repositories cache and install additional packages
      apt:
        pkg:
          - ocl-icd-libopencl1
          - beignet-opencl-icd
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Plex
      apt:
        deb: https://downloads.plex.tv/plex-media-server-new/1.25.8.5621-7a6fed0cf/debian/plexmediaserver_1.25.8.5621-7a6fed0cf_amd64.deb
