---
- name: Install dotnet core SDK
  hosts: all
  become: yes

  tasks:
    - name: Install dotnet6
      apt:
        name: dotnet6
        state: present
        update_cache: yes

    - name: Install dotnet7
      apt:
        name: dotnet7
        state: present

    - name: Install dotnet8
      apt:
        name: dotnet8
        state: present
