- name: Install neovim
  hosts: "*"
  tasks:

    - name: Clone neovim
      git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: "{{ lookup('env', 'HOME') }}/neovim"
        update: yes
        force: yes

    - name: Install build dependencies
      ansible.builtin.apt:
        pkg:
          - ninja-build
          - gettext
          - libtool
          - libtool-bin
          - autoconf
          - automake
          - cmake
          - g++
          - pkg-config
          - unzip
          - curl
          - doxygen
      become: true

    - name: Check if Plug is already installed
      stat:
        path: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/autoload/plug.vim"
      register: plug_file

    - name: Install plug
      shell: |
        sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      when: plug_file.stat.exists == False

    - name: Build neovim
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
      become: true

    - name: Install neovim
      become: true
      shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
