- name: Install ansible
  hosts: "*"
  gather_facts: true
  become: true
  tasks:

    - name: Add apt-repository ppa:ansible/ansible
      apt_repository:
        repo: ppa:ansible/ansible
      when: ansible_distribution == 'Ubuntu'

    - name: Install Ansible
      ansible.builtin.apt:
        update_cache: yes
        name: ansible
        state: latest
      when: ansible_distribution == 'Ubuntu'
