---
- name: Update servers
  hosts: all
  become: yes

  tasks:
    - name: Run apt upgrade
      ansible.builtin.apt:
        upgrade: 'yes'
        update_cache: 'yes'

    - name: Run dist-upgrade
      ansible.builtin.apt:
        upgrade: 'dist'
    
    - name: Run autoremove
      ansible.builtin.apt:
        autoremove: 'yes'
